<?php
namespace fonclub\ocmodulegenerator\models;

use yii\base\Model;

/**
 * Class Generator
 * @author fonclub
 * @created 10.10.2018
 * @package fonclub\ocmodulegenerator\models
 */
class Generator extends Model
{
    public $title;
    public $name;
    public $version;
    public $author;

    public function init()
    {
        $this->author = 'fonclub';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['title', 'name', 'version', 'author'], 'required'],
            [['title', 'name'], 'string', 'max' => 50],
            ['name', 'match', 'pattern' => '/^[a-z-_]\w*$/i']
        ];
    }

    public function attributeLabels()
    {
        return [
            'title'   => 'Module title',
            'name'    => 'Module name (like: my_module, mymodule)',
            'version' => 'Opencart version',
            'author'  => 'Author',
        ];
    }

    public function renderModuleFile($file, $params = [])
    {
        extract($params);
        $content = file_get_contents($file);

        foreach ($params as $key => $value) {
            $content = str_replace("{{{$key}}}", $value, $content);
        }

        return $content;
    }

    public function getDirContents($dir, &$results = array())
    {
        $files = scandir($dir);

        foreach ($files as $key => $value) {
            $path = realpath($dir.DIRECTORY_SEPARATOR.$value);
            if (is_file($path)) {
                $results[] = $path;
            } else {
                if ($value != "." && $value != "..") {
                    $this->getDirContents($path, $results);

                    if (is_file($path)) {
                        $results[] = $path;
                    }
                }
            }
        }

        return $results;
    }
}